import json, copy

slot_alignment = {
    # source language: target language
    '3.0T MRI': '3.0T MRI',
    '4WD': '사륜구동',
    'CPU': 'CPU',
    'CPU model': 'CPU 모델',
    'CT': 'CT',
    'DSA': 'DSA',
    'Douban score': 'Douban 평점',
    'GPU category': 'GPU 유형',
    'GPU model': 'GPU 평점',
    'UV intensity': '자외선 강도',
    'address': '주소',
    'area': '지역',
    'arrival time': '도착시간',
    'brand': '상표',
    'bus routes': '버스 노선',
    'business hours': '업무 시간',
    'campus': '캠퍼스',
    'city': '도시',
    'class cabin': '객실 등급',
    'class number': '수업 번호',
    'classification': '분류',
    'classroom': '강의실',
    'colour': '색',
    'computer type': '컴퓨터 종류',
    'consumption': '소비',
    'cruise control system': '크루즈 컨트롤 시스템',
    'cuisine': '요리',
    'date': '날짜',
    'day': '요일',
    'decade': '10년',
    'departure': '출발',
    'departure time': '출발 시간',
    'destination': '목적지',
    'director': '감독',
    'dishes': '요리',
    'duration': '기간',
    'end date': '종료일',
    'end time': '종료 시간',
    'episode length': '회당 길이',
    'episodes': '에피소드',
    'features': '특징',
    'film length': '상영 길이',
    'flight information': '항공편 정보',
    'fuel consumption': '연료 소비량',
    'game performance': '게임 성능',
    'general or specialized': '종합 또는 전문',
    'grade': '성적',
    'hard disk capacity': '하드디스크 용량',
    'heated seats': '열선 시트',
    'hotel type': '호텔 종류',
    'hours': '시간',
    'hybrid': '하이브리드',
    'key departments': '주요 부서',
    'level': '단계',
    'localized': '현지화된',
    'memory capacity': '메모리 용량',
    'metro station': '지하철역',
    'name': '이름',
    'name list': '명단',
    'number of seats': '좌석수',
    'opening hours': '영업 시간',
    'operating system': '운영 체제',
    'parking': '주차',
    'parking assist system': '주차 보조 시스템',
    'per capita consumption': '일 인당 소비량',
    'phone': '전화',
    'phone number': '전화번호',
    'power level': '출력 수준',
    'premiere time': '첫 방영 시간',
    'price': '가격',
    'pricerange': '가격대',
    'product name': '상품명',
    'production country or area': '제작 국가 또는 제작 지역',
    'public or private': '공립 또는 사립',
    'punctuality rate': '정시율',
    'registration time': '등록 시간',
    'release date': '개봉일',
    'room charge': '객실 요금',
    'room type': '객실 타입',
    'score': '점수',
    'screen size': '화면 크기',
    'seat type': '좌석 종류',
    'series': '시리즈',
    'service time': '진료 시간',
    'size': '크기',
    'standby time': '대기 시간',
    'star': '주연',
    'start date': '시작일',
    'start time': '시작 시간',
    'subject': '주제',
    'tamperature': '기온',
    'teacher': '선생님',
    'the most suitable people': '가장 적당한 사람',
    'ticket price': '표 가격',
    'time': '시간',
    'times': '시간',
    'title': '제목',
    'train number': '기차 번호',
    'type': '종류',
    'usage': '사용',
    'ventilated seats': '통풍 시트',
    'weather condition': '기상 상황',
    'weight': '무게',
    'wind': '바람',
}

# BDSL
new_slot_alignment = copy.copy(slot_alignment)
key_dic = {}
slot_key_list = list(slot_alignment.keys())
for key in slot_key_list:
    new_key = key.replace(" ", "_")
    new_key = new_key.lower()
    new_slot_alignment[new_key] = new_slot_alignment.pop(key)

slot_key_list = list(slot_alignment.keys())
for key in slot_key_list:
    new_value = new_slot_alignment[key]
    new_value = new_value.replace(" ", "_")
    new_slot_alignment[key] = new_value.lower()

print(slot_alignment)
with open("./slot_alignment.json", "w") as f:
    json.dump(new_slot_alignment, f, ensure_ascii=False, indent=4)